#!/usr/bin/env bash

file=~/lib/todo

date_fmt="'%y %b %_d"

date_sep=" – "

have() {
	command -v "$1" >& /dev/null;
}

_todo_show() {
	if have nl; then
		nl -ba -w3 -s". " "$file"
	else
		local i=0
		while IFS='' read -r line; do
			printf '%3d%s%s\n' $((++i)) ". " "$line"
		done < "$file"
	fi
}

todo() {
	if [[ $1 == /* ]]; then
		local addr=$1
		if [[ $addr != /*/ ]]; then
			addr+=/
		fi
		_todo_show | sed -n "${addr}p"
	elif [[ $1 ]]; then
		echo "$(date +"$date_fmt")$date_sep$*" >> "$file"
		_todo_show | tail -n 1
	elif [[ -s ~/lib/todo ]]; then
		_todo_show
	fi
}

vitodo() {
	eval "${EDITOR:-vi} ~/lib/todo"
}

rmtodo() {
	local addr=${1:-'$'}
	local tmp=${file%/*}/.todo.tmp
	if [[ $addr == /* && $addr != /*/ ]]; then
		addr+=/
	fi
	_todo_show | sed -n "${addr}p" &&
	sed "${addr}d" "$file" > "$tmp" &&
	cp "$tmp" "$file" &&
	rm -f "$tmp"
}

if [[ ! -d ${file%/*} ]]; then
	mkdir -p "${file%/*}"
fi

if [[ -f ~/todo ]] && [[ ! -e $file ]]; then
	mv ~/todo "$file"
	ln -s 'lib/todo' ~/todo
fi

cmd=${0##*/}

case $cmd in
    todo|vitodo|rmtodo)
	$cmd "$@";;
    *)
	todo;;
esac
